### ISSUE TITLE
CUDA incompatibility

### ISSUE THREAD

**Issue by Cazforshort** [hustvl/GaussianDreamer#1]
There seems to be some CUDA incompatibility with diff-gaussian-rasterization.

` File "C:\Users\xxx\Programs\miniconda\envs\gau_env\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects`

**Comment by taoranyi** [comment]
Thank you for your attention. As you know, #2 is a similar issue. I will try to solve this problem later when I have time.

**Comment by taoranyi** [comment]
Let's discuss this issue in #2 , and I will close this issue.
