### ISSUE TITLE
About initializing point clouds

### ISSUE THREAD

**Issue by ch1998** [hustvl/GaussianDreamer#10]
Hi，
in your project page，your use the point clouds with the added ground to initialize the 3D Gaussians.
If I want to modify the initialized point cloud similarly, how should I import the point cloud?

Regards

**Comment by taoranyi** [comment]
Hi, you can see this code:
`    def add_bg(self,coords,rgb):
        num_pts = 30000
        bound = 0.4
        xy = 5.0
        z_coords = coords[:, 2] 
        min_value = np.min(z_coords)  
        xyz = np.random.random((num_pts, 3)) * np.array([[xy, xy, bound]]) - np.array([[xy/2.0,xy/2.0, 4.0 * bound/5.0]])+ np.array([[0,0,min_value]])
        shs = np.random.random((num_pts, 3)) / 255.0
        colors = SH2RGB(shs)
        all_coords = np.concatenate([coords,xyz],axis=0)
        all_rgb = np.concatenate([rgb,colors],axis=0)
        return all_coords,all_rgb`
      And you can use this function in https://github.com/hustvl/GaussianDreamer/blob/ad96913c6582cb876cd8137ec7fd4c0b237b2750/threestudio/systems/GaussianDreamer.py#L221
