### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by TLB-MISS** [hustvl/GaussianDreamer#2]
First of all, thank you so much for revealing this wonderful work!

I tried setting up the environment following the instructions in the ReadMe, but the same error as shown [here](https://github.com/dreamgaussian/dreamgaussian/issues/6) appears.
However, the solutions on that page will not solve my problem. This is because that solution requires the latest torch and the latest diff-gaussian-rasterization, while GaussianDreamer does not use the latest diff-gaussian-rasterization(There are some modules whose input/output is different from the latest version).

**My environment**
GPU : A5000
CUDA : 11.8 or 11.7
torch : 1.12.1 or 2.0.0 or 2.0.1 (I am getting the same error while installing diff-gaussian-rasterization in all versions.)

Could you please give me some advice?
Thanks.

**Comment by taoranyi** [comment]
Thank you for your attention. I'm sorry that I haven't tested on Windows. One solution is to replace the current implementation with the latest diff-gaussian-rasterization and remove the depth output during rendering. I will try to solve this problem later when I have time.

**Comment by TLB-MISS** [comment]
@taoranyi 

Oh, I'm using ubuntu.
This issue also occurred when installing DreamGaussian, but in the case of DreamGaussian, it was resolved with the solution [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645).

**Comment by taoranyi** [comment]
Here is a possible way. Currently, our diff-gaussian-rasterization comes from [here](https://github.com/ingra14m/depth-diff-gaussian-rasterization), which you can replace with this: [diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization). It is worth noting that the [rasterizer](https://github.com/hustvl/GaussianDreamer/blob/95147e6fff21edd4048a414dc9da73c5d697c5bd/gaussiansplatting/gaussian_renderer/__init__.py#L85) should be modified appropriately. If this works, please let me know!

**Comment by TLB-MISS** [comment]
@taoranyi 

I already tried it yesterday. However, as you said, the input/output had to be modified, so I didn't look into it in depth.

I don't have time to look into the rasterizer right now, so I'll try tomorrow or the day after!

**Comment by taoranyi** [comment]
Thanks!!!!!!!!!!!!!! I will be very grateful!

**Comment by Cazforshort** [comment]
I was able to get it up and running by downloading [this rasterizer](https://github.com/graphdeco-inria/diff-gaussian-rasterization) and running these exact steps.

I don't think it everything is playing well since it doesn't seem like it is outputting any results anywhere, but maybe I just don't know what to look for?

> conda create -n gau_env python=3.9
> conda activate gau_env
> conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
> pip install ninja
> pip install -r requirements.txt
> cd ..
> pip install gaussian-splatting/submodules/diff-gaussian-rasterization
> pip install gaussian-splatting/submodules/simple-knn
> cd shap-e
> pip install -e .pip install -e .
> pip install bitsandbytes-windows
> conda install -c anaconda ipywidgets
> pip install open3d
> python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"

Not sure if this helps at all, but here the output:
<img width="1232" alt="image" src="https://github.com/hustvl/GaussianDreamer/assets/6918831/e32f05d4-4d94-4fe8-847f-65c9b8d3f756">

**Comment by Cazforshort** [comment]
> Here is a possible way. Currently, our diff-gaussian-rasterization comes from [here](https://github.com/ingra14m/depth-diff-gaussian-rasterization), which you can replace with this: [diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization). It is worth noting that the [rasterizer](https://github.com/hustvl/GaussianDreamer/blob/95147e6fff21edd4048a414dc9da73c5d697c5bd/gaussiansplatting/gaussian_renderer/__init__.py#L85) should be modified appropriately. If this works, please let me know!

I get a ton of errors when trying to install that other replacement for some reason. Ends about the same as the other errors though.

File "C:\Users\xxx\Programs\miniconda\envs\gau_env\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\Users\xxx\Programs\miniconda\envs\gau_env\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff-gaussian-rasterization
  Running setup.py clean for diff-gaussian-rasterization
Failed to build diff-gaussian-rasterization

**Comment by TLB-MISS** [comment]
@taoranyi  @Cazforshort 

I fixed it.

1. Erase original `diff-gaussian-rasterization` directory
2. `git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization` in `GaussianDreamer/gaussiansplatting/submodules`
3. Follow the instructions [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645)
4. `pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization`
5. Fix [`raster_settings`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L36) : Add `debug=False` as the last argument
6. Fix [`rasterizer`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L85) : `rendered_image, radii, depth, _ =` Because lastest gaussian rasterizers output alpha values.

**Comment by TLB-MISS** [comment]
@taoranyi 

I have additional question.
How can I get 3D mesh?
It seems that GaussianDreamer can only output point clouds.

**Comment by Cazforshort** [comment]
> @taoranyi @Cazforshort
> 
> I fixed it.
> 
> 1. Erase original `diff-gaussian-rasterization` directory
> 2. `git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization` in `GaussianDreamer/gaussiansplatting/submodules`
> 3. Follow the instructions [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645)
> 4. `pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization`
> 5. Fix [`raster_settings`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L36) : Add `debug=False` as the last argument
> 6. Fix [`rasterizer`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L85) : `rendered_image, radii, depth, _ =` Because lastest gaussian rasterizers output alpha values.

You were able to get it to work with cuda 11.8? I thought only 11.7 would work with 2.0.1 pytorch

**Comment by Cazforshort** [comment]
The raster changes worked for me too, but I had to stick with cuda 11.7 not 11.8.
It also saves  a copy of the entire codebase each time? Thats a weird one.

**Comment by taoranyi** [comment]
@TLB-MISS 
I haven't yet touched on how to convert a 3D Gaussians into a mesh, so you may have to look it up yourself.

**Comment by y-71** [comment]
I've created a 

> @taoranyi @Cazforshort
> 
> I fixed it.
> 
> 1. Erase original `diff-gaussian-rasterization` directory
> 2. `git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization` in `GaussianDreamer/gaussiansplatting/submodules`
> 3. Follow the instructions [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645)
> 4. `pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization`
> 5. Fix [`raster_settings`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L36) : Add `debug=False` as the last argument
> 6. Fix [`rasterizer`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L85) : `rendered_image, radii, depth, _ =` Because lastest gaussian rasterizers output alpha values.

I've created a fork with the changes, i initially did it to make it work on colab, so for the lazy people out there, help yourself.

**Comment by Cazforshort** [comment]
> > @taoranyi @Cazforshort
> > I fixed it.
> > 
> > 1. Erase original `diff-gaussian-rasterization` directory
> > 2. `git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization` in `GaussianDreamer/gaussiansplatting/submodules`
> > 3. Follow the instructions [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645)
> > 4. `pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization`
> > 5. Fix [`raster_settings`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L36) : Add `debug=False` as the last argument
> > 6. Fix [`rasterizer`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L85) : `rendered_image, radii, depth, _ =` Because lastest gaussian rasterizers output alpha values.
> 
> I've created a fork with the changes, i initially did it to make it work on colab, so for the lazy people out there, help yourself.
> 
> https://github.com/y-71/GaussianDreamer/

Where are you getting the ply? I'm just seeing pictures when I run the training example.

**Comment by TLB-MISS** [comment]
@Cazforshort 

I don't know exactly what your situation is. In my case, there was a ply file in the save folder.

**Comment by TLB-MISS** [comment]
I think this issue can be closed

**Comment by TLB-MISS** [comment]
I think this issue can be closed

**Comment by Cazforshort** [comment]
> @Cazforshort
> 
> I don't know exactly what your situation is. In my case, there was a ply file in the save folder.

Ah something must be wrong since I don't have a save folder after training.

**Comment by cwwjyh** [comment]
> I was able to get it up and running by downloading [this rasterizer](https://github.com/graphdeco-inria/diff-gaussian-rasterization) and running these exact steps.
> 
> I don't think it everything is playing well since it doesn't seem like it is outputting any results anywhere, but maybe I just don't know what to look for?
> 
> EDIT: I forgot to mention that I added torch=2.0.1 to the requirements file since it kept getting upgraded!
> 
> > conda remove -n gau_env --all
> > conda create -n gau_env python=3.9
> > conda activate gau_env
> > conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
> > pip install ninja
> > pip install -r requirements.txt
> > cd ..
> > pip install gaussian-splatting/submodules/diff-gaussian-rasterization
> > pip install gaussian-splatting/submodules/simple-knn
> > cd .\GaussianDreamer\shap-e
> > pip install -e .
> > pip install bitsandbytes-windows
> > conda install -c anaconda ipywidgets
> > pip install open3d
> > conda install -c conda-forge plyfile
> 
> > python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"
> 
> Not sure if this helps at all, but here the output: <img alt="image" width="1232" src="https://user-images.githubusercontent.com/6918831/276745190-e32f05d4-4d94-4fe8-847f-65c9b8d3f756.png">

i run the follow success:
pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117
pip install ninja
pip install -r requirements.txt
then it will appear :
torchaudio 2.0.2+cu117 requires torch==2.0.1, but you have torch 2.1.0 which is incompatible.
fix use:
pip install torch==2.0.1 torchvision===0.15.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install xformers==0.0.20

git clone https://github.com/hustvl/GaussianDreamer.git 
cd GaussianDreamer
pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization
pip install ./gaussiansplatting/submodules/simple-knn
git clone https://github.com/openai/shap-e.git
cd shap-e
pip install -e .

pip install ipywidgets
pip install open3d
pip install plyfile

python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"

Then it can be running

**Comment by ch1998** [comment]
> I was able to get it up and running by downloading [this rasterizer](https://github.com/graphdeco-inria/diff-gaussian-rasterization) and running these exact steps.
> 
> I don't think it everything is playing well since it doesn't seem like it is outputting any results anywhere, but maybe I just don't know what to look for?
> 
> EDIT: I forgot to mention that I added torch=2.0.1 to the requirements file since it kept getting upgraded!
> 
> > conda remove -n gau_env --all
> > conda create -n gau_env python=3.9
> > conda activate gau_env
> > conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
> > pip install ninja
> > pip install -r requirements.txt
> > cd ..
> > pip install gaussian-splatting/submodules/diff-gaussian-rasterization
> > pip install gaussian-splatting/submodules/simple-knn
> > cd .\GaussianDreamer\shap-e
> > pip install -e .
> > pip install bitsandbytes-windows
> > conda install -c anaconda ipywidgets
> > pip install open3d
> > conda install -c conda-forge plyfile
> 
> > python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"
> 
> Not sure if this helps at all, but here the output: <img alt="image" width="1232" src="https://private-user-images.githubusercontent.com/6918831/276745190-e32f05d4-4d94-4fe8-847f-65c9b8d3f756.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTUxMTgsIm5iZiI6MTcwMTMxNDgxOCwicGF0aCI6Ii82OTE4ODMxLzI3Njc0NTE5MC1lMzJmMDVkNC00ZDk0LTRmZTgtODQ3Zi02NWM5YjhkM2Y3NTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDMyNjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjJlN2E0ZjM3OTZiYWNjODdmMjZlMmVjMTU5YTdkNTVmNGY2YjNiNDA5Njg1NzBkYjhjODMzZDI4MGNkZjA4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qdpbp6k-KC2qoas15MpQpWjuQweGrPJu3SDX5snGIr4">

Why is your training speed so fast? I am also running on RTX3090, but it is only 1.30Mib/s. My installation is torch2.0.1+cuda11.8
![image](https://github.com/hustvl/GaussianDreamer/assets/37291486/ea97b875-e873-457e-acb2-f50ee2a49a09)

**Comment by tsabbir96** [comment]
> > @taoranyi @Cazforshort
> > I fixed it.
> > 
> > 1. Erase original `diff-gaussian-rasterization` directory
> > 2. `git clone --recursive https://github.com/ashawkey/diff-gaussian-rasterization` in `GaussianDreamer/gaussiansplatting/submodules`
> > 3. Follow the instructions [here](https://github.com/dreamgaussian/dreamgaussian/issues/6#issuecomment-1742200645)
> > 4. `pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization`
> > 5. Fix [`raster_settings`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L36) : Add `debug=False` as the last argument
> > 6. Fix [`rasterizer`](https://github.com/hustvl/GaussianDreamer/blob/main/gaussiansplatting/gaussian_renderer/__init__.py#L85) : `rendered_image, radii, depth, _ =` Because lastest gaussian rasterizers output alpha values.
> 
> I've created a fork with the changes, i initially did it to make it work on colab, so for the lazy people out there, help yourself.
> 
> https://github.com/y-71/GaussianDreamer/

@y-71 that's so cool, I am struggling really hard to get it installed on Colab.. What did you do? I faced so much issue but finally was able to get it up and running. I wanted to know what you did to understand if we both were getting same errors.. Would you like to share the link to the colab notebook?
