### ISSUE TITLE
ply sotre the color info?

### ISSUE THREAD

**Issue by Justinfungi** [hustvl/GaussianDreamer#22]
I have run through the demo. however, it seems all 3 types of ply file do not store the color info.  I would like to ask if it is intentionally hided or the color information is stored in another place

![image_720](https://github.com/hustvl/GaussianDreamer/assets/79019929/070318fb-6e19-4547-83c4-8837ebb04869)

**Comment by taoranyi** [comment]
Hello, the point cloud here saves color information.
https://github.com/hustvl/GaussianDreamer/blob/0005b2e87b0605f11579efac0813a7e3bbb28952/threestudio/systems/GaussianDreamer.py#L514
