### ISSUE TITLE
How to render the image with white background?

### ISSUE THREAD

**Issue by WayneCV** [hustvl/GaussianDreamer#25]
Hi, in the test stage, the rendered image usually has a black background. How to set the background to white (e.g., the examples in the paper have the white background)? Thanks in advance.

**Comment by SPTAU** [comment]
[Here](https://github.com/hustvl/GaussianDreamer/blob/9c3312829a2c0d499e8e65246540360db9dae1f3/threestudio/systems/GaussianDreamer.py#L94)
