### ISSUE TITLE
GPU Not Called

### ISSUE THREAD

**Issue by dqsz0193** [hustvl/GaussianDreamer#26]
Hi, thank you for your work!
When running the `python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"`, it turns out that the server didn't use the GPU for computing. I waited a few hours but the training didn't stop and the epoch stay zero.
![2](https://github.com/hustvl/GaussianDreamer/assets/164178761/0f0674c4-23f0-464b-835c-27af9858daa9)
However the server has RTX4090 and the terminal logs as follow.
![QQ图片20240321233110](https://github.com/hustvl/GaussianDreamer/assets/164178761/7a83e23f-b5d1-4ddb-aafb-68b8198654ae)

**Comment by taoranyi** [comment]
Hello, this may actually download the diffusion model weight. After the download is completed, you can start running.
