### ISSUE TITLE
ERROR: Could not build wheels for pysdf, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by hxj2580** [hustvl/GaussianDreamer#29]
Building wheel for pysdf (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      Couldn't find Eigen locally, downloading...
      Download failed, failed to find Eigen
      /root/miniconda3/envs/gsdreamer/lib/python3.8/site-packages/setuptools/dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      /root/miniconda3/envs/gsdreamer/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      /root/miniconda3/envs/gsdreamer/lib/python3.8/site-packages/setuptools/dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!
      
              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.
      
              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
      
              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************
      
      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_ext
      creating tmp
      gcc -pthread -B /root/miniconda3/envs/gsdreamer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/envs/gsdreamer/include/python3.8 -c /tmp/tmp7w08eov2.cpp -o tmp/tmp7w08eov2.o -std=c++17
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      gcc -pthread -B /root/miniconda3/envs/gsdreamer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/miniconda3/envs/gsdreamer/include/python3.8 -c /tmp/tmpfr8_j62z.cpp -o tmp/tmpfr8_j62z.o -fvisibility=hidden
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      building 'pysdf' extension
      creating build
      creating build/temp.linux-x86_64-cpython-38
      creating build/temp.linux-x86_64-cpython-38/src
      gcc -pthread -B /root/miniconda3/envs/gsdreamer/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DVERSION_INFO=\"0.1.9\" -Iinclude -I/tmp/pip-install-vcdmzce5/pysdf_3724183e41c94b2daf0a27b5ffd821c7/.eggs/pybind11-2.12.0-py3.8.egg/pybind11/include -INone -I/root/miniconda3/envs/gsdreamer/include/python3.8 -c pybind.cpp -o build/temp.linux-x86_64-cpython-38/pybind.o -std=c++17 -fvisibility=hidden
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      In file included from pybind.cpp:2:
      include/sdf/sdf.hpp:30:10: fatal error: Eigen/Core: No such file or directory
         30 | #include <Eigen/Core>
            |          ^~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysdf
  Running setup.py clean for pysdf
  Building wheel for envlight (setup.py) ... done
  Created wheel for envlight: filename=envlight-0.1.0-py3-none-any.whl size=40356 sha256=53a786eff12886c57c4b7fc41e178a6dc5167bcebf39985ff7a2771b481dc0de
  Stored in directory: /tmp/pip-ephem-wheel-cache-j5iar851/wheels/d8/70/df/657fc3444e6c70f214ea65eddcd49a9c5536b1ee738829ccc3
  Building wheel for clip (setup.py) ... done
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369497 sha256=a9470bb8449ab0f0af314b3b7be0be3a0604694c89e8faf21ff28997bea290a1
  Stored in directory: /tmp/pip-ephem-wheel-cache-j5iar851/wheels/ab/4f/3a/5e51521b55997aa6f0690e095c08824219753128ce8d9969a3
Successfully built nerfacc tinycudann nvdiffrast envlight clip
Failed to build pysdf
ERROR: Could not build wheels for pysdf, which is required to install pyproject.toml-based projects

**Comment by lqyyykx** [comment]
Do you solve this problem now?I have the same question.
