### ISSUE TITLE
export?

### ISSUE THREAD

**Issue by MattFog** [hustvl/GaussianDreamer#3]
this is great! is there any way to export as a density field / volume data / point cloud?

**Comment by taoranyi** [comment]
Hello, MattFog. Thank you for your attention, [this](https://github.com/hustvl/GaussianDreamer/blob/95147e6fff21edd4048a414dc9da73c5d697c5bd/threestudio/systems/GaussianDreamer.py#L484) should be what you are looking for.

**Comment by MattFog** [comment]
thanks so much!

i almost have this installed - it looks like the dependencies use CUDA 11 (not the latest version, 12) - which I don't think you have any control over - but just surfacing it in case you didn't know it's outdated.

Excited to try it out!
