### ISSUE TITLE
Halfway through the execution, there was no response

### ISSUE THREAD

**Issue by CuzKy** [hustvl/GaussianDreamer#30]
I encountered this situation when running this code on both RTX3090 and RTX3080. When I reached this state, there was no next step. At most, I ran it for almost 4 hours without taking any further steps, and my memory status did not change during the run.
![1712131905660](https://github.com/hustvl/GaussianDreamer/assets/138789659/08d82ef3-4b7b-4f74-910a-30fcfa20b621)
![1](https://github.com/hustvl/GaussianDreamer/assets/138789659/4da9c417-2c6c-4aee-9a19-f6b06829ff7e)
![2](https://github.com/hustvl/GaussianDreamer/assets/138789659/a392cc5c-31a9-4e8f-ab20-477aa568e202)

**Comment by taoranyi** [comment]
Hello, this may actually download the diffusion model weight or the program crashed.
