### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by SpyAlan** [hustvl/GaussianDreamer#34]
when run the code in colab:
!python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox" data.batch_size=2

there is a probelm:
TypeError:
GaussianRasterizationSettings.__new__() missing 1 required positional argument: 'debug'

**Comment by Zhao-Yihao** [comment]
I suppose that you have installed a wrong gaussian rasterization, try to install the version in the source code of this project and remember to download g++project.
