### ISSUE TITLE
could not build wheels for diff-gaussian-rasterization

### ISSUE THREAD

**Issue by lqyyykx** [hustvl/GaussianDreamer#38]
<img width="944" alt="截屏2024-07-03 下午7 00 12" src="https://github.com/hustvl/GaussianDreamer/assets/100980008/91c90381-fb01-424c-a864-646911f77d9a">
Failed to build diff-gaussian-rasterization
ERROR: Could not build wheels for diff-gaussian-rasterization, which is required to install pyproject.toml-based projects

**Comment by XiaozhenQiao** [comment]
I encountered the same problem, how to solve it?
