### ISSUE TITLE
Ply Compatibility

### ISSUE THREAD

**Issue by Cazforshort** [hustvl/GaussianDreamer#7]
I was able to run the process without issue, but the PLYs that are being generated don't seem to be working for me in any of the Gaussian splat viewers.

Is the structure unique in some way?

I tested in [the Unity Viewer](https://github.com/aras-p/UnityGaussianSplatting) as well as on [Poly.cam](https://poly.cam/gaussian-splatting).

The error I get in the unity viewer is that  there is a "PLY vertex size mismatch, expected 248 but file has 27".
That is after running the example train in your readme.

I've attached them for your review.
[plyfiles.zip](https://github.com/hustvl/GaussianDreamer/files/13252359/plyfiles.zip)

Regards,
Caz

**Comment by taoranyi** [comment]
Thank you for your attention. Are you using a file named last.ply in zip?

**Comment by taoranyi** [comment]
I think our work can be well applied to the game, and I hope we can explore this issue together!

**Comment by taoranyi** [comment]
I fixed this problem, just raising the sh degree to 3. [This]{https://drive.google.com/file/d/1ieeB-Q8NLZDV0X_zrUG6GgPvTUgNpDt8/view?usp=sharing} is the code and ply file.
![cba1e27decdda17d003fcff5172e2a5](https://github.com/hustvl/GaussianDreamer/assets/64740876/c3318746-02cf-475a-bcc8-e8c8e0e2e698)
![627bb9ea82cee8d2d19c6f78715bc99](https://github.com/hustvl/GaussianDreamer/assets/64740876/0cc4c0a6-e971-4f45-982a-2569d10d5258)
