### ISSUE TITLE
question about training 

### ISSUE THREAD

**Issue by ch1998** [hustvl/GaussianDreamer#9]
Hello, I successfully ran the code, but when the training reached normal level, the program did not continue. Is there any error?
There is stabilityai/stable-diffusion-2-1-base in gaussiandreamer-sd.yaml. Is it because I did not download the pre-trained model?
![image](https://github.com/hustvl/GaussianDreamer/assets/37291486/8cdbd3ac-0a25-4ce0-83b7-f5e9111cf288)

**Comment by tsabbir96** [comment]
Hi @ch1998 , were you successful in running the code? I mean I wanted to test the capabilities by giving prompt and checking what it generated. but the main issue is running the following command starts a training session which I dont want:
`python launch.py --config configs/gaussiandreamer-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a fox"`

Did you find a way to test the model out-of-the-box without training it ?

**Comment by ch1998** [comment]
Sorry, I completed the training but didn't find a way to test it directly.

**Comment by ch1998** [comment]
Training takes about 10 minutes. 
install step：
pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
pip install ninja
Modify xformers==0.0.20 in requirements.txt
pip install -r requirements.txt

git clone https://github.com/hustvl/GaussianDreamer.git
cd GaussianDreamer
pip install ./gaussiansplatting/submodules/diff-gaussian-rasterization
pip install ./gaussiansplatting/submodules/simple-knn
git clone https://github.com/openai/shap-e.git
cd shap-e
pip install -e .

pip install open3d
pip install plyfile

Please refer to #2 .

**Comment by tsabbir96** [comment]
@ch1998 great thanks... just one question i saw you have `requirements.txt` file even before cloning the `GaussianDreamer` Repo..
THe only `requirements.txt` file I saw is inside the repo.. Where did you get the `requirements.txt` before cloning the repo?

**Comment by ch1998** [comment]
> @ch1998 great thanks... just one question i saw you have `requirements.txt` file even before cloning the `GaussianDreamer` Repo.. THe only `requirements.txt` file I saw is inside the repo.. Where did you get the `requirements.txt` before cloning the repo?

first，git clone https://github.com/hustvl/GaussianDreamer.git
then，other steps.
Sorry, the steps are in the wrong order.

**Comment by tsabbir96** [comment]
@ch1998 could you tell me which GPU you used to reduce the training time to 10 mins, I am using T4 GPU on COlab and the time it takes is rediculously long.

**Comment by ch1998** [comment]
I am using a 3090. The first run will take some time. Some shape-e related files will be generated, which will take about an hour. Then there will be formal training, which will take about 10 minutes.

**Comment by CuzKy** [comment]
> Hello, I successfully ran the code, but when the training reached normal level, the program did not continue. Is there any error? There is stabilityai/stable-diffusion-2-1-base in gaussiandreamer-sd.yaml. Is it because I did not download the pre-trained model? ![image](https://private-user-images.githubusercontent.com/37291486/286531794-8cdbd3ac-0a25-4ce0-83b7-f5e9111cf288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzI3NTEsIm5iZiI6MTcxMjEzMjQ1MSwicGF0aCI6Ii8zNzI5MTQ4Ni8yODY1MzE3OTQtOGNkYmQzYWMtMGEyNS00Y2UwLTgzYjctZjVlOTExMWNmMjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4MjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGQ1YjIzZGM3MDAwMjA4NjMzYTJkMjZlZTY0OWMzOWQ5ODhmMDYxZDA0OWRhNWVhNjdlZGNhYmFhODJjY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bxhBu-8xqkHRc5PzmebMvIUNHw4RU2n94e6797C6AO8)

i met the same problem.I encountered this situation when running this code on both RTX3090 and RTX3080. When I reached this state, there was no next step. At most, I ran it for almost 4 hours without taking any further steps, and my memory status did not change during the run.
![1712131905660](https://github.com/hustvl/GaussianDreamer/assets/138789659/caeea5e1-0f13-452f-94e1-8c909d429fb9)
![1](https://github.com/hustvl/GaussianDreamer/assets/138789659/a500ce68-2adb-4528-aaff-348c82051da6)
![2](https://github.com/hustvl/GaussianDreamer/assets/138789659/ce7e8f96-18e9-49e1-9f35-1bb8d9c76d48)
how can i sovel it?thanks!!!!!!!
